### ISSUE TITLE
Option to be able to set "server"

### ISSUE THREAD

**Issue by 7MinSec** [techspence/ADeleginator#1]
Hello,

A friend recommended adeleg to me, and by way of that search I found your tool which looks interesting!   When I ran on an engagement I got an error about:

`Unable to find a domain controller automatically, please specify one manually using --server`

The error looks like it comes from the PowerShell script but is from the run of `adeleg.exe.`. Could you include an option in your script to be able to specify the server on the fly?

Thanks,
Brian

**Comment by techspence** [comment]
Hey @7MinSec thank you for the recommendation. This should fix it, but let me know if it does not. 🙏https://github.com/techspence/ADeleginator/commit/13b52f61d2227deb2dbf378ef5702d686543f100

**Comment by 7MinSec** [comment]
That worked like a charm, thanks much @techspence !

**Comment by techspence** [comment]
Awesome. Thank you!
